# Generated by Django 3.2.16 on 2023-11-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231128_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='pub_date',
        ),
    ]
